# Generated by Django 4.2.17 on 2025-10-15 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseware', '0017_financialassistanceconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('section_id', models.CharField(max_length=255)),
                ('unit_id', opaque_keys.edx.django.models.UsageKeyField(max_length=255)),
                ('template_id', models.IntegerField()),
                ('quiz_data', models.JSONField()),
                ('score', models.FloatField()),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courseware_quizresult',
                'unique_together': {('user', 'section_id', 'unit_id', 'template_id')},
            },
        ),
    ]
