# Generated by Django 4.2.17 on 2025-08-16 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('txn_ref', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='vnpay', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_type', models.CharField(choices=[('single_course', 'Single Course'), ('all_access', 'All Access Subscription')], default='single_course', max_length=20)),
                ('course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enrollment_created', models.BooleanField(default=False)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('enrollment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('failed', 'Failed')], default='pending', max_length=20, null=True)),
                ('subscription_active', models.BooleanField(default=False)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transaction',
            },
        ),
    ]
