# Generated by Django 4.2.17 on 2025-08-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS payment_transaction (
                id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
                user_id int NOT NULL,
                amount decimal(10,2) NOT NULL,
                currency varchar(3) NOT NULL DEFAULT 'VND',
                txn_ref varchar(100) NOT NULL UNIQUE,
                payment_method varchar(50) NOT NULL DEFAULT 'vnpay',
                payment_status varchar(20) NOT NULL DEFAULT 'pending',
                payment_type varchar(20) NOT NULL DEFAULT 'single_course',
                course_id varchar(100) NULL,
                course_name varchar(200) NULL,
                enrollment_created tinyint(1) NOT NULL DEFAULT 0,
                enrollment_date datetime NULL,
                subscription_active tinyint(1) NOT NULL DEFAULT 0,
                subscription_expires_at datetime NULL,
                created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                CONSTRAINT payment_transaction_user_id_fk FOREIGN KEY (user_id) REFERENCES auth_user (id)
            );
            """,
            "DROP TABLE IF EXISTS payment_transaction;"
        )
    ]
