# Generated by Django 4.2.17 on 2025-11-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20250816_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='section_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('single_course', 'Single Course'), ('all_access', 'All Access Subscription'), ('section_access', 'Section Access')], default='single_course', max_length=20),
        ),
    ]
