# Generated by Django 4.2.17 on 2025-11-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_add_section_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='allowed_sections_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='excluded_sections_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
